/** Tables 0001→0024 — ordre d'INSERT (parents avant enfants). */
export const CAMPUS_BACKUP_INSERT_ORDER = [
  "teachers",
  "classrooms",
  "school_years",
  "school_weeks",
  "school_day_exceptions",
  "subjects",
  "memberships",
  "membership_subjects",
  "student_accesses",
  "publication_templates",
  "agenda_items",
  "timetable_imports",
  "timetable_slots",
  "timetable_class_mappings",
  "timetable_teacher_codes",
  "school_branches",
  "school_professions",
  "pedagogical_contexts",
  "admin_code_counters",
  "school_classes",
  "pedagogical_paths",
  "annual_courses",
  "teacher_course_assignments",
  "teacher_course_assignment_events",
  "annual_course_notes",
  "course_schedule_slots",
  "class_attendance_days",
  "teacher_setups",
  "teacher_notes",
] as const;

export type CampusBackupTableName = (typeof CAMPUS_BACKUP_INSERT_ORDER)[number];

export const CAMPUS_BACKUP_DELETE_ORDER = [...CAMPUS_BACKUP_INSERT_ORDER].reverse();

export const BACKUP_FORMAT_VERSION_V4 = 4 as const;

export type BackupColumnType = "text" | "integer" | "flag";

export interface BackupColumnSpec {
  name: string;
  type: BackupColumnType;
  /** Identité / intégrité : absente → snapshot v4 refusé. */
  required?: boolean;
}

function cols(...specs: BackupColumnSpec[]): BackupColumnSpec[] {
  return specs;
}

/** Schéma v4 : seules ces colonnes sont acceptées à la restauration. */
export const CAMPUS_BACKUP_COLUMNS: Record<CampusBackupTableName, BackupColumnSpec[]> = {
  teachers: cols(
    { name: "id", type: "text", required: true },
    { name: "display_name", type: "text", required: true },
    { name: "initials", type: "text", required: true },
    { name: "password_hash", type: "text", required: true },
    { name: "created_at", type: "text" },
    { name: "is_admin", type: "flag", required: true },
    { name: "is_active", type: "flag", required: true },
    { name: "must_change_password", type: "flag" },
    { name: "password_updated_at", type: "text" },
    { name: "archived_at", type: "text" },
    { name: "last_login_at", type: "text" },
    { name: "teaching_type", type: "text" },
  ),
  classrooms: cols(
    { name: "id", type: "text", required: true },
    { name: "name", type: "text", required: true },
    { name: "program_label", type: "text" },
    { name: "access_code_hint", type: "text" },
    { name: "created_at", type: "text" },
    { name: "school_class_id", type: "text" },
  ),
  school_years: cols(
    { name: "id", type: "text", required: true },
    { name: "label", type: "text", required: true },
    { name: "status", type: "text", required: true },
    { name: "starts_on", type: "text", required: true },
    { name: "ends_on", type: "text", required: true },
    { name: "source_filename", type: "text" },
    { name: "imported_at", type: "text" },
    { name: "activated_at", type: "text" },
    { name: "created_at", type: "text" },
  ),
  school_weeks: cols(
    { name: "school_year_id", type: "text", required: true },
    { name: "week_number", type: "integer", required: true },
    { name: "week_kind", type: "text", required: true },
    { name: "monday", type: "text", required: true },
  ),
  school_day_exceptions: cols(
    { name: "school_year_id", type: "text", required: true },
    { name: "day_date", type: "text", required: true },
    { name: "day_state", type: "text", required: true },
    { name: "label", type: "text" },
    { name: "updated_at", type: "text" },
  ),
  subjects: cols(
    { name: "id", type: "text", required: true },
    { name: "classroom_id", type: "text", required: true },
    { name: "name", type: "text", required: true },
    { name: "annual_course_id", type: "text" },
  ),
  memberships: cols(
    { name: "id", type: "text", required: true },
    { name: "teacher_id", type: "text", required: true },
    { name: "classroom_id", type: "text", required: true },
    { name: "valid_from", type: "text" },
    { name: "valid_to", type: "text" },
  ),
  membership_subjects: cols(
    { name: "membership_id", type: "text", required: true },
    { name: "subject_id", type: "text", required: true },
  ),
  student_accesses: cols(
    { name: "id", type: "text", required: true },
    { name: "classroom_id", type: "text", required: true },
    { name: "label", type: "text", required: true },
    { name: "access_code_hash", type: "text" },
  ),
  publication_templates: cols(
    { name: "id", type: "text", required: true },
    { name: "owner_teacher_id", type: "text", required: true },
    { name: "title", type: "text", required: true },
    { name: "detail", type: "text" },
    { name: "type", type: "text", required: true },
    { name: "subject_id", type: "text" },
    { name: "default_school_week_number", type: "integer" },
    { name: "default_day", type: "integer" },
    { name: "source_school_year_id", type: "text" },
    { name: "source_item_id", type: "integer" },
    { name: "created_at", type: "text" },
    { name: "updated_at", type: "text" },
  ),
  agenda_items: cols(
    { name: "id", type: "integer", required: true },
    { name: "classroom_id", type: "text", required: true },
    { name: "subject_id", type: "text", required: true },
    { name: "author_teacher_id", type: "text", required: true },
    { name: "day", type: "integer", required: true },
    { name: "hour", type: "integer", required: true },
    { name: "week_offset", type: "integer" },
    { name: "type", type: "text", required: true },
    { name: "title", type: "text", required: true },
    { name: "detail", type: "text" },
    { name: "created_at", type: "text" },
    { name: "updated_at", type: "text" },
    { name: "school_week_number", type: "integer" },
    { name: "template_id", type: "text" },
    { name: "school_year_id", type: "text" },
    { name: "annual_course_id", type: "text" },
    { name: "course_session_key", type: "text" },
    { name: "course_session_date", type: "text" },
    { name: "reference_session_id", type: "text" },
    { name: "reference_item_id", type: "text" },
  ),
  timetable_imports: cols(
    { name: "id", type: "text", required: true },
    { name: "school_year_id", type: "text" },
    { name: "source_filename", type: "text", required: true },
    { name: "school_year_label", type: "text" },
    { name: "source_version", type: "text" },
    { name: "status", type: "text", required: true },
    { name: "slot_count", type: "integer" },
    { name: "excluded_sps_count", type: "integer" },
    { name: "warnings_json", type: "text" },
    { name: "imported_at", type: "text" },
  ),
  timetable_slots: cols(
    { name: "id", type: "text", required: true },
    { name: "import_id", type: "text", required: true },
    { name: "class_code", type: "text", required: true },
    { name: "day_of_week", type: "integer", required: true },
    { name: "period", type: "integer", required: true },
    { name: "branch_label", type: "text" },
    { name: "teacher_code", type: "text" },
    { name: "week_kind", type: "text", required: true },
  ),
  timetable_class_mappings: cols(
    { name: "import_id", type: "text", required: true },
    { name: "class_code", type: "text", required: true },
    { name: "classroom_id", type: "text", required: true },
  ),
  timetable_teacher_codes: cols(
    { name: "import_id", type: "text", required: true },
    { name: "teacher_code", type: "text", required: true },
    { name: "teacher_id", type: "text" },
  ),
  school_branches: cols(
    { name: "id", type: "text", required: true },
    { name: "code", type: "text", required: true },
    { name: "label", type: "text", required: true },
    { name: "sort_order", type: "integer" },
    { name: "is_active", type: "flag", required: true },
    { name: "created_at", type: "text" },
    { name: "archived_at", type: "text" },
    { name: "admin_code", type: "text" },
    { name: "teaching_type", type: "text" },
  ),
  school_professions: cols(
    { name: "id", type: "text", required: true },
    { name: "admin_code", type: "text", required: true },
    { name: "label", type: "text", required: true },
    { name: "duration_years", type: "integer" },
    { name: "sort_order", type: "integer" },
    { name: "is_active", type: "flag", required: true },
    { name: "archived_at", type: "text" },
    { name: "created_at", type: "text" },
    { name: "class_code_prefix", type: "text" },
  ),
  pedagogical_contexts: cols(
    { name: "id", type: "text", required: true },
    { name: "admin_code", type: "text", required: true },
    { name: "profession_id", type: "text", required: true },
    { name: "training_year", type: "integer", required: true },
    { name: "branch_id", type: "text", required: true },
    { name: "is_active", type: "flag", required: true },
    { name: "archived_at", type: "text" },
    { name: "created_at", type: "text" },
  ),
  admin_code_counters: cols(
    { name: "kind", type: "text", required: true },
    { name: "next_value", type: "integer", required: true },
  ),
  school_classes: cols(
    { name: "id", type: "text", required: true },
    { name: "code", type: "text", required: true },
    { name: "label", type: "text", required: true },
    { name: "sort_order", type: "integer" },
    { name: "is_active", type: "flag", required: true },
    { name: "school_year_label", type: "text" },
    { name: "created_at", type: "text" },
    { name: "profession_id", type: "text" },
    { name: "training_year", type: "integer" },
    { name: "school_year_id", type: "text" },
    { name: "parallel_code", type: "text" },
    { name: "is_archived", type: "flag" },
    { name: "archived_at", type: "text" },
  ),
  pedagogical_paths: cols(
    { name: "context_id", type: "text", required: true },
    { name: "path_json", type: "text", required: true },
    { name: "updated_at", type: "text" },
  ),
  annual_courses: cols(
    { name: "id", type: "text", required: true },
    { name: "school_year_id", type: "text", required: true },
    { name: "class_id", type: "text", required: true },
    { name: "context_id", type: "text", required: true },
    { name: "archived_at", type: "text" },
    { name: "created_at", type: "text" },
    { name: "updated_at", type: "text" },
  ),
  teacher_course_assignments: cols(
    { name: "id", type: "text", required: true },
    { name: "annual_course_id", type: "text", required: true },
    { name: "teacher_id", type: "text", required: true },
    { name: "role", type: "text", required: true },
    { name: "valid_from", type: "text", required: true },
    { name: "valid_to", type: "text" },
    { name: "created_by_admin_id", type: "text" },
    { name: "created_at", type: "text" },
    { name: "ended_at", type: "text" },
    { name: "override_reason", type: "text" },
    { name: "override_by_admin_id", type: "text" },
  ),
  teacher_course_assignment_events: cols(
    { name: "id", type: "text", required: true },
    { name: "annual_course_id", type: "text", required: true },
    { name: "assignment_id", type: "text" },
    { name: "teacher_id", type: "text", required: true },
    { name: "admin_id", type: "text", required: true },
    { name: "kind", type: "text", required: true },
    { name: "role", type: "text" },
    { name: "detail", type: "text" },
    { name: "created_at", type: "text" },
  ),
  annual_course_notes: cols(
    { name: "id", type: "text", required: true },
    { name: "school_year_id", type: "text", required: true },
    { name: "class_id", type: "text", required: true },
    { name: "context_id", type: "text", required: true },
    { name: "reference_session_id", type: "text" },
    { name: "author_teacher_id", type: "text", required: true },
    { name: "text", type: "text", required: true },
    { name: "source_note_id", type: "text" },
    { name: "source_school_year_id", type: "text" },
    { name: "inherited_at", type: "text" },
    { name: "created_at", type: "text" },
    { name: "updated_at", type: "text" },
    { name: "annual_course_id", type: "text" },
  ),
  course_schedule_slots: cols(
    { name: "id", type: "text", required: true },
    { name: "annual_course_id", type: "text", required: true },
    { name: "day_of_week", type: "integer", required: true },
    { name: "period_start", type: "integer", required: true },
    { name: "period_end", type: "integer", required: true },
    { name: "week_kind", type: "text", required: true },
    { name: "valid_from", type: "text" },
    { name: "valid_to", type: "text" },
    { name: "created_at", type: "text" },
    { name: "updated_at", type: "text" },
  ),
  class_attendance_days: cols(
    { name: "id", type: "text", required: true },
    { name: "class_id", type: "text", required: true },
    { name: "day_of_week", type: "integer", required: true },
    { name: "week_kind", type: "text", required: true },
    { name: "role", type: "text", required: true },
    { name: "created_at", type: "text" },
    { name: "updated_at", type: "text" },
  ),
  teacher_setups: cols(
    { name: "teacher_id", type: "text", required: true },
    { name: "config_json", type: "text", required: true },
    { name: "updated_at", type: "text" },
  ),
  teacher_notes: cols(
    { name: "teacher_id", type: "text", required: true },
    { name: "notes_json", type: "text", required: true },
    { name: "updated_at", type: "text" },
  ),
};

/** FK non nulle → la référence doit exister dans le snapshot, même si le parent est vide. */
export const CAMPUS_BACKUP_FOREIGN_KEYS: Array<{
  table: CampusBackupTableName;
  column: string;
  parent: CampusBackupTableName;
  parentColumn: string;
}> = [
  { table: "school_weeks", column: "school_year_id", parent: "school_years", parentColumn: "id" },
  { table: "school_day_exceptions", column: "school_year_id", parent: "school_years", parentColumn: "id" },
  { table: "subjects", column: "classroom_id", parent: "classrooms", parentColumn: "id" },
  { table: "memberships", column: "teacher_id", parent: "teachers", parentColumn: "id" },
  { table: "memberships", column: "classroom_id", parent: "classrooms", parentColumn: "id" },
  { table: "membership_subjects", column: "membership_id", parent: "memberships", parentColumn: "id" },
  { table: "membership_subjects", column: "subject_id", parent: "subjects", parentColumn: "id" },
  { table: "student_accesses", column: "classroom_id", parent: "classrooms", parentColumn: "id" },
  { table: "publication_templates", column: "owner_teacher_id", parent: "teachers", parentColumn: "id" },
  { table: "agenda_items", column: "classroom_id", parent: "classrooms", parentColumn: "id" },
  { table: "agenda_items", column: "subject_id", parent: "subjects", parentColumn: "id" },
  { table: "agenda_items", column: "author_teacher_id", parent: "teachers", parentColumn: "id" },
  { table: "timetable_slots", column: "import_id", parent: "timetable_imports", parentColumn: "id" },
  { table: "timetable_class_mappings", column: "import_id", parent: "timetable_imports", parentColumn: "id" },
  { table: "timetable_class_mappings", column: "classroom_id", parent: "classrooms", parentColumn: "id" },
  { table: "timetable_teacher_codes", column: "import_id", parent: "timetable_imports", parentColumn: "id" },
  { table: "pedagogical_contexts", column: "profession_id", parent: "school_professions", parentColumn: "id" },
  { table: "pedagogical_contexts", column: "branch_id", parent: "school_branches", parentColumn: "id" },
  { table: "school_classes", column: "school_year_id", parent: "school_years", parentColumn: "id" },
  { table: "school_classes", column: "profession_id", parent: "school_professions", parentColumn: "id" },
  { table: "pedagogical_paths", column: "context_id", parent: "pedagogical_contexts", parentColumn: "id" },
  { table: "annual_courses", column: "school_year_id", parent: "school_years", parentColumn: "id" },
  { table: "annual_courses", column: "class_id", parent: "school_classes", parentColumn: "id" },
  { table: "annual_courses", column: "context_id", parent: "pedagogical_contexts", parentColumn: "id" },
  { table: "teacher_course_assignments", column: "annual_course_id", parent: "annual_courses", parentColumn: "id" },
  { table: "teacher_course_assignments", column: "teacher_id", parent: "teachers", parentColumn: "id" },
  { table: "teacher_course_assignment_events", column: "annual_course_id", parent: "annual_courses", parentColumn: "id" },
  { table: "teacher_course_assignment_events", column: "teacher_id", parent: "teachers", parentColumn: "id" },
  { table: "annual_course_notes", column: "school_year_id", parent: "school_years", parentColumn: "id" },
  { table: "annual_course_notes", column: "class_id", parent: "school_classes", parentColumn: "id" },
  { table: "annual_course_notes", column: "context_id", parent: "pedagogical_contexts", parentColumn: "id" },
  { table: "annual_course_notes", column: "author_teacher_id", parent: "teachers", parentColumn: "id" },
  { table: "course_schedule_slots", column: "annual_course_id", parent: "annual_courses", parentColumn: "id" },
  { table: "classrooms", column: "school_class_id", parent: "school_classes", parentColumn: "id" },
  { table: "subjects", column: "annual_course_id", parent: "annual_courses", parentColumn: "id" },
  { table: "agenda_items", column: "annual_course_id", parent: "annual_courses", parentColumn: "id" },
  { table: "class_attendance_days", column: "class_id", parent: "school_classes", parentColumn: "id" },
  { table: "teacher_setups", column: "teacher_id", parent: "teachers", parentColumn: "id" },
  { table: "teacher_notes", column: "teacher_id", parent: "teachers", parentColumn: "id" },
];
