export {
  notebookUnlinkedCourseReason,
  resolveCatalogClassroomId,
  resolveDefaultSubjectId,
  resolveNotebookClassroomId,
  resolveNotebookSubjectId,
  weekdayToCourseDayIndex,
  weekNotesKey,
  type NotebookRuntimeClassroom,
  type NotebookRuntimeSubject,
} from "./resolve.ts";
export {
  filterNotebookItemsForSubject,
  notebookContextFromCourse,
  openCourseInWeekTarget,
  type NotebookCourseContext,
} from "./open-course.ts";
export {
  appendWeekNote,
  classNotesStorageKey,
  clearNotesFromBrowser,
  composeWeekNotesDoc,
  createEmptyNotesDocument,
  isClassNotesPayload,
  loadNotesFromBrowser,
  listWeekNotes,
  moveWeekNote,
  normalizeClassNotes,
  parseStoredNotes,
  peekNotesFromBrowser,
  removeWeekNote,
  saveNotesToBrowser,
  serializeClassNotes,
  setWeekRichNote,
} from "./notes-storage.ts";
export {
  CAMPUS_RICH_DETAIL_PREFIX,
  CAMPUS_RICH_FORMAT,
  QUICK_BLOCK_KINDS,
  QUICK_BLOCK_LABELS,
  RICH_HIGHLIGHT_HEX,
  RICH_TEXT_COLOR_HEX,
  RICH_TEXT_COLOR_IDS,
  decodeRichDetail,
  emptyRichDoc,
  encodeRichDetail,
  excerptRichDoc,
  fromPlainLines,
  fromPlainText,
  htmlToSafeInlines,
  insertQuickBlock,
  isEmptyRichDoc,
  isPlaceholderDetail,
  isRichDetail,
  publicationTitleForDoc,
  rejectDangerousRichPayload,
  sanitizeHref,
  sanitizeRichDoc,
  type CampusRichDoc,
  type QuickBlockKind,
  type RichBlock,
  type RichInline,
  type RichMarks,
  type RichTextColorId,
} from "./rich-doc.ts";
export {
  buildPublicationPayload,
  cloneRichDoc,
  composeWeekPublicationDoc,
  findCarnetPublicationItem,
  isCarnetOwnedPublication,
  isPublicationLine,
  listFoldableCarnetPublications,
  previousSchoolWeekNumber,
} from "./rich-agenda.ts";
export {
  clampWeekDisplayCount,
  formatWeekColumnLabel,
  formatWeekColumnSubtitle,
  visibleSchoolWeeks,
  type WeekDisplayCount,
} from "./week-window.ts";
export type { ClassNotesDocument, NotebookClipboard, TeacherWeekNote } from "./types.ts";
